SEVERITY_ICON = {'FAIL': 'CANCEL', 'INFO': 'INFO'}
CATEGORY_ICON = {
    'GEOMETRY': 'MESH_DATA',
    'TRANSFORM': 'OBJECT_ORIGIN',
    'UV': 'UV',
    'NAMING': 'SORTALPHA',
    'MATERIAL': 'MATERIAL',
}
